version: '3'
services:
    generator:
        container_name: generator
        build: .
        ports:
            - 8080:8080
        networks:
            - my-network
networks:
    my-network:
        driver: bridge
